### ISSUE TITLE
Different warning for unregistered ID

### ISSUE THREAD

**Issue by morbidick** [fablab-ka/LasaurApp#11]
Currently the warning for an unregistered card and for an empty card reader are the same and very misleading.

**Comment by Philip-Caroli** [comment]
Fixed, different Warnings are now shown, depending on the cause of the failure.
Following texts can get shown:
"Missing ID Card"
"Unregistered ID Card"
"Unactivated ID Card"
"Unassigned ID Card"
"User not allowed"
