### ISSUE TITLE
Webinterface vom Internet abhängig

### ISSUE THREAD

**Issue by wkraft-fablabka** [fablab-ka/LasaurApp#18]
Es werden diverse Javascript-Bibliotheken aus dem Internet verwendet.
Wenn kein Internet vorhanden ist und der Browser diese nicht mehr im Cache hat, kann der Lasersaur nicht bedient werden!
Es handelt sich um mindestens:
bootstartp.min
jquery

Dies Bibliotheken müssen lokal hinterlegt werden, dass wir auch ohne Internet lasern können

**Comment by Philip-Caroli** [comment]
Fixed
