### ISSUE TITLE
LasaurApp nun abhängig von pyscard

### ISSUE THREAD

**Issue by wkraft-fablabka** [fablab-ka/LasaurApp#19]
Die Lasersaur-App ist nun abhängig von PyScard. Das lässt sich unter Windows extrem schwer und unter Linux auch nur mit entsprechenden zusätzlichen Paketen installieren.

Die LasuarApp sollte jedoch möglichst Out-Of the Box laufen.

Vorschlag:  Odoo Anbindung in ein eigenes Programm auslagern, das lokale Kopien aller Datenbanken (material, User, ...) lokal als JSON ablegt.

Die LasaurApp greift dann nur noch auf die Bibliotheken zu und bleibt auch lokal startbar. Wir können dann auch Dummy-Materialbibliotheken mitausliefern!

**Comment by Philip-Caroli** [comment]
Odoo hat mit PyCard nichts zu tun.
Die unnötige Einbindung on odoo_remote hab ich entfernt, mein Fehler.
Ich bin dagegen odoo zu externalisieren, weil ich mit der Einbindung noch einiges vorhabe. Es kann aber ein Interface "InformationProvider" o.ä. geben, wohinter man dann "odoo", "odoobutwithoutodoo" oder "none" setzen kann.

Vorschlag: das Karten-System entfernen, da es keinen Mehrwert sondern nur Probleme bringt.

**Comment by Philip-Caroli** [comment]
Da die Kartenprüfung entfernt wurde, ist auch die Abhängigkeit weg.
