### ISSUE TITLE
GUI: Pass-Form has linebreak where it shouldn't

### ISSUE THREAD

**Issue by Vikath** [fablab-ka/LasaurApp#3]
See attached screenshot. Occurs on Firefox and Chromium. 

![screenshot - 08 04 2016 - 15 05 11](https://cloud.githubusercontent.com/assets/478957/14436464/1af03614-001d-11e6-93e4-a3ddaf279a18.png)

**Comment by mostley** [comment]
can't reproduce with latest firefox (45) and chrome (49) versions. Which versions are failing for you?

**Comment by Vikath** [comment]
Problem not occuring anymore, unknown reason.
