### ISSUE TITLE
GUI: Arrows at Move/Jog are out of Place

### ISSUE THREAD

**Issue by Vikath** [fablab-ka/LasaurApp#4]
See attached Screenshot. Occurs on my Firefox and Chromium.

![screenshot - 11 04 2016 - 19 42 27](https://cloud.githubusercontent.com/assets/478957/14436637/ee1f26c6-001d-11e6-9cf6-e02088fdbbc7.png)

**Comment by mostley** [comment]
can't reproduce with current firefox or chrome versions, which version does the ui glitch happen?

**Comment by Vikath** [comment]
Problem not occuring anymore, unknown reason.
